routes:
  # English
  /en/:
    template: home-en
    data: page.home-en
  /en/about/:
    template: page-lang
    data: page.about-en
  /en/video-series/:
    template: page-lang
    data: page.video-serie-en
  /en/events/:
    template: page-lang
    data: page.eventi-en
  /en/research/:
    template: page-lang
    data: page.ricerca-en

  # German
  /de/:
    template: home-de
    data: page.home-de
  /de/about/:
    template: page-lang
    data: page.about-de
  /de/videoreihe/:
    template: page-lang
    data: page.video-serie-de
  /de/veranstaltungen/:
    template: page-lang
    data: page.eventi-de
  /de/forschung/:
    template: page-lang
    data: page.ricerca-de

  # Spanish
  /es/:
    template: home-es
    data: page.home-es
  /es/acerca-de/:
    template: page-lang
    data: page.about-es
  /es/serie-de-videos/:
    template: page-lang
    data: page.video-serie-es
  /es/eventos/:
    template: page-lang
    data: page.eventi-es
  /es/investigacion/:
    template: page-lang
    data: page.ricerca-es

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
